#!/bin/bash
#ffmpeg -i Untitled.m4v -vf "scale=trunc(iw/4)*2:trunc(ih/4)*2" -c:v libx265 -crf 28   output-half.mp4
#ffmpeg -i $1 -vf "scale=trunc(iw/4)*2:trunc(ih/4)*2" -c:v libx265 -crf 28   output-half.mp4
#ffmpeg -i $1 -vf scale="720:-1" -c:v libx265 -crf 28   output-half.mp4
#ffmpeg -i $1 -vf scale=w=-4:h=240  -c:v libx265 -crf 28   output-half.mp4
#ffmpeg -i $1 -vf scale=w=-4:h=360  -c:v libx265 -crf 28   output-half.mp4
#ffmpeg -i $1 -vf scale=w=-4:h=200  -c:v libx265 -crf 28   output-half.mp4



#vertical
#ffmpeg -i $1 -vf scale=w=-4:h=480  -c:v libx265 -crf 28   output-half.mp4
#ffmpeg -i $1 -vf scale=w=-4:h=960  -c:v libx265 -crf 28   output-half.mp4
#ffmpeg -i $1 -vf scale=w=-4:h=800  -c:v libx265 -crf 28   output-half.mp4



# NO AUDIO = -an
#ffmpeg -i $1 -vf scale=w=-4:h=920  -c:v libx265 -crf 28  -an  output-half.mp4

#save color
ffmpeg -i $1 -vf "scale=640:640:force_original_aspect_ratio=decrease,pad=ceil(iw/2)*2:ceil(ih/2)*2" -vcodec libx264 -crf 17 -pix_fmt yuv420p -bsf:v h264_metadata=video_full_range_flag=0:colour_primaries=9:transfer_characteristics=18:matrix_coefficients=9 ./output-half.mp4

